<%@ Page Title="Student Grid Operations" Language="VB" MasterPageFile="~/Site.Master" AutoEventWireup="false" CodeFile="StudentGridOperations.aspx.vb" Inherits="GridOperations_StudentGridOperations" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
<div class="card">
<div class="card-header bg-dark text-white">Student Grid Operations</div>
<div class="card-body">
<asp:GridView ID="gvStudents" runat="server" AutoGenerateColumns="False" AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" CssClass="table table-bordered">
<Columns>
<asp:BoundField DataField="StudentID" HeaderText="ID" ReadOnly="True" />
<asp:BoundField DataField="StudentName" HeaderText="Student Name" />
<asp:BoundField DataField="Gender" HeaderText="Gender" />
</Columns>
</asp:GridView>
</div>
</div>
</asp:Content>